import type {
  User,
  ProducerProfile,
  Batch,
  Product,
  ProductVariant,
  Order,
  Review,
  VerificationSubmission,
} from '@/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'buyer@example.com',
    phone: '0412345678',
    role: 'consumer',
    status: 'active',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-2',
    email: 'producer@goldenhive.com.au',
    phone: '0423456789',
    role: 'producer',
    status: 'active',
    createdAt: '2024-06-15T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'user-3',
    email: 'producer@sunnymeadows.com.au',
    role: 'producer',
    status: 'active',
    createdAt: '2024-08-20T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'user-4',
    email: 'admin@hivejoy.com.au',
    role: 'admin',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
];

// Mock Producers
export const mockProducers: ProducerProfile[] = [
  {
    id: 'producer-1',
    userId: 'user-2',
    businessName: 'Golden Hive Apiaries',
    abn: '12345678901',
    address: {
      street: '123 Honey Lane',
      suburb: 'Beechworth',
      state: 'VIC',
      postcode: '3747',
      country: 'Australia',
    },
    bio: 'Family-owned apiary in the heart of Victorian high country. We\'ve been producing premium raw honey for over 30 years, using traditional beekeeping methods passed down through generations. Our bees forage on pristine native bushland.',
    profileImage: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400',
    coverImage: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1200',
    verificationStatus: 'approved',
    badgeLevel: 'verified',
    createdAt: '2024-06-15T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'producer-2',
    userId: 'user-3',
    businessName: 'Sunny Meadows Honey',
    abn: '98765432101',
    address: {
      street: '456 Blossom Road',
      suburb: 'Mudgee',
      state: 'NSW',
      postcode: '2850',
      country: 'Australia',
    },
    bio: 'Boutique honey producer specializing in single-origin wildflower and eucalyptus varieties. Our hives are located in protected bushland areas, producing honey with unique terroir.',
    profileImage: 'https://images.unsplash.com/photo-1471943311424-646960669fbc?w=400',
    coverImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200',
    verificationStatus: 'approved',
    badgeLevel: 'premium',
    createdAt: '2024-08-20T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'producer-3',
    userId: 'user-5',
    businessName: 'Tasmania Pure Honey',
    address: {
      street: '78 Wilderness Way',
      suburb: 'Huonville',
      state: 'TAS',
      postcode: '7109',
      country: 'Australia',
    },
    bio: 'Premium Leatherwood honey from the pristine Tasmanian wilderness. Our bees have exclusive access to ancient rainforests.',
    profileImage: 'https://images.unsplash.com/photo-1550411294-098c0dc9db6f?w=400',
    verificationStatus: 'submitted',
    badgeLevel: 'none',
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
];

// Mock Batches
export const mockBatches: Batch[] = [
  {
    id: 'batch-1',
    producerId: 'producer-1',
    region: 'Beechworth, Victoria',
    harvestDate: '2024-12-15',
    extractionDate: '2024-12-18',
    floralSourceTags: ['Yellow Box', 'Ironbark', 'Native Wildflowers'],
    notes: 'Exceptional clarity this season. Strong floral notes with hints of caramel.',
    status: 'active',
    createdAt: '2024-12-18T00:00:00Z',
    updatedAt: '2024-12-18T00:00:00Z',
  },
  {
    id: 'batch-2',
    producerId: 'producer-1',
    region: 'Alpine High Country, Victoria',
    harvestDate: '2024-11-20',
    extractionDate: '2024-11-22',
    floralSourceTags: ['Snow Gum', 'Mountain Ash'],
    notes: 'Limited alpine harvest with distinctive eucalyptus character.',
    status: 'active',
    createdAt: '2024-11-22T00:00:00Z',
    updatedAt: '2024-11-22T00:00:00Z',
  },
  {
    id: 'batch-3',
    producerId: 'producer-2',
    region: 'Mudgee, New South Wales',
    harvestDate: '2024-12-01',
    extractionDate: '2024-12-03',
    floralSourceTags: ['Blue Gum', 'Clover', 'Lucerne'],
    notes: 'Light golden color with mild, sweet flavor profile.',
    status: 'active',
    createdAt: '2024-12-03T00:00:00Z',
    updatedAt: '2024-12-03T00:00:00Z',
  },
  {
    id: 'batch-4',
    producerId: 'producer-2',
    region: 'Hunter Valley, New South Wales',
    harvestDate: '2024-10-15',
    extractionDate: '2024-10-17',
    floralSourceTags: ['Manuka', 'Tea Tree'],
    status: 'active',
    createdAt: '2024-10-17T00:00:00Z',
    updatedAt: '2024-10-17T00:00:00Z',
  },
];

// Helper to create variants
const createVariants = (productId: string, basePrice: number, stock: number): ProductVariant[] => [
  {
    id: `${productId}-250g`,
    productId,
    size: '250g',
    price: basePrice,
    stock,
    weight: 250,
  },
  {
    id: `${productId}-500g`,
    productId,
    size: '500g',
    price: basePrice * 1.8,
    stock: Math.floor(stock * 0.8),
    weight: 500,
  },
  {
    id: `${productId}-1kg`,
    productId,
    size: '1kg',
    price: basePrice * 3.2,
    stock: Math.floor(stock * 0.5),
    weight: 1000,
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: 'product-1',
    producerId: 'producer-1',
    batchId: 'batch-1',
    title: 'Yellow Box Raw Honey',
    description: 'Our signature Yellow Box honey is renowned for its smooth, buttery flavor with subtle citrus undertones. Harvested from bees foraging on native Yellow Box eucalyptus in the Victorian high country. Perfect for drizzling on toast, adding to tea, or enjoying straight from the jar.',
    photos: [
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800',
      'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800',
    ],
    status: 'approved',
    variants: createVariants('product-1', 18.50, 50),
    createdAt: '2024-12-20T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'product-2',
    producerId: 'producer-1',
    batchId: 'batch-2',
    title: 'Alpine Snow Gum Honey',
    description: 'A rare treat from our high-altitude hives. This limited-edition honey captures the essence of the Victorian Alps with its distinctive menthol-eucalyptus notes and crystalline amber color. Each jar is numbered from this small-batch harvest.',
    photos: [
      'https://images.unsplash.com/photo-1471943311424-646960669fbc?w=800',
    ],
    status: 'approved',
    variants: createVariants('product-2', 24.00, 20),
    createdAt: '2024-11-25T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 'product-3',
    producerId: 'producer-2',
    batchId: 'batch-3',
    title: 'Mudgee Wildflower Blend',
    description: 'A delightful blend of wildflower nectars from the rolling hills of Mudgee wine country. Light and floral with notes of clover and native blossoms. Pairs beautifully with cheese boards and fresh bread.',
    photos: [
      'https://images.pexels.com/photos/5634208/pexels-photo-5634208.jpeg?w=800',
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800',
    ],
    status: 'approved',
    variants: createVariants('product-3', 16.00, 75),
    createdAt: '2024-12-10T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'product-4',
    producerId: 'producer-2',
    batchId: 'batch-4',
    title: 'Hunter Valley Manuka Honey',
    description: 'Premium Australian Manuka honey with verified MGO rating. Known for its distinctive earthy flavor and potential wellness benefits. Dark amber color with a thick, luxurious texture.',
    photos: [
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800',
    ],
    status: 'approved',
    variants: [
      {
        id: 'product-4-250g',
        productId: 'product-4',
        size: '250g',
        price: 35.00,
        stock: 30,
        weight: 250,
      },
      {
        id: 'product-4-500g',
        productId: 'product-4',
        size: '500g',
        price: 65.00,
        stock: 20,
        weight: 500,
      },
    ],
    createdAt: '2024-10-20T00:00:00Z',
    updatedAt: '2024-12-15T00:00:00Z',
  },
  {
    id: 'product-5',
    producerId: 'producer-1',
    batchId: 'batch-1',
    title: 'Ironbark Honey - Dark & Rich',
    description: 'Bold and robust Ironbark honey with deep amber color and complex flavor profile. Notes of molasses and eucalyptus. Excellent for baking and marinades.',
    photos: [
      'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800',
    ],
    status: 'approved',
    variants: createVariants('product-5', 20.00, 40),
    createdAt: '2024-12-22T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
];

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: 'order-1',
    buyerId: 'user-1',
    sellerId: 'producer-1',
    items: [
      {
        id: 'item-1',
        orderId: 'order-1',
        variantId: 'product-1-500g',
        productId: 'product-1',
        productTitle: 'Yellow Box Raw Honey',
        variantSize: '500g',
        quantity: 2,
        unitPrice: 33.30,
        gst: 3.03,
        batchSnapshot: {
          batchId: 'batch-1',
          region: 'Beechworth, Victoria',
          harvestDate: '2024-12-15',
          floralSources: ['Yellow Box', 'Ironbark'],
        },
      },
    ],
    subtotal: 66.60,
    shippingCost: 12.00,
    platformFee: 6.66,
    gstTotal: 6.06,
    total: 84.66,
    status: 'delivered',
    shippingAddress: {
      street: '10 Sample Street',
      suburb: 'Melbourne',
      state: 'VIC',
      postcode: '3000',
      country: 'Australia',
    },
    trackingNumber: 'AP123456789AU',
    carrier: 'Australia Post',
    createdAt: '2024-12-28T10:00:00Z',
    updatedAt: '2025-01-02T14:00:00Z',
  },
  {
    id: 'order-2',
    buyerId: 'user-1',
    sellerId: 'producer-2',
    items: [
      {
        id: 'item-2',
        orderId: 'order-2',
        variantId: 'product-4-250g',
        productId: 'product-4',
        productTitle: 'Hunter Valley Manuka Honey',
        variantSize: '250g',
        quantity: 1,
        unitPrice: 35.00,
        gst: 3.18,
        batchSnapshot: {
          batchId: 'batch-4',
          region: 'Hunter Valley, NSW',
          harvestDate: '2024-10-15',
          floralSources: ['Manuka', 'Tea Tree'],
        },
      },
    ],
    subtotal: 35.00,
    shippingCost: 10.00,
    platformFee: 3.50,
    gstTotal: 3.18,
    total: 48.18,
    status: 'shipped',
    shippingAddress: {
      street: '10 Sample Street',
      suburb: 'Melbourne',
      state: 'VIC',
      postcode: '3000',
      country: 'Australia',
    },
    trackingNumber: 'AP987654321AU',
    carrier: 'Australia Post',
    createdAt: '2025-01-05T09:00:00Z',
    updatedAt: '2025-01-06T11:00:00Z',
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    orderId: 'order-1',
    buyerId: 'user-1',
    sellerId: 'producer-1',
    productId: 'product-1',
    rating: 5,
    comment: 'Absolutely delicious honey! The flavor is incredible and you can really taste the difference from supermarket honey. Will definitely order again.',
    createdAt: '2025-01-03T10:00:00Z',
  },
  {
    id: 'review-2',
    orderId: 'order-prev-1',
    buyerId: 'user-6',
    sellerId: 'producer-1',
    productId: 'product-2',
    rating: 5,
    comment: 'The Alpine honey is exceptional. Such a unique flavor profile. Worth every cent!',
    createdAt: '2024-12-20T15:00:00Z',
  },
  {
    id: 'review-3',
    orderId: 'order-prev-2',
    buyerId: 'user-7',
    sellerId: 'producer-2',
    productId: 'product-3',
    rating: 4,
    comment: 'Lovely light honey, perfect for everyday use. Fast shipping too.',
    createdAt: '2025-01-01T09:00:00Z',
  },
];

// Mock Verification Submissions (for admin)
export const mockVerifications: VerificationSubmission[] = [
  {
    id: 'verification-1',
    producerId: 'producer-3',
    documents: [
      {
        id: 'doc-1',
        type: 'business_registration',
        name: 'Business Registration.pdf',
        url: '/documents/business-reg.pdf',
        uploadedAt: '2025-01-02T08:00:00Z',
      },
      {
        id: 'doc-2',
        type: 'beekeeper_registration',
        name: 'TAS Beekeeper License.pdf',
        url: '/documents/beekeeper.pdf',
        uploadedAt: '2025-01-02T08:05:00Z',
      },
    ],
    submittedAt: '2025-01-02T08:10:00Z',
  },
];

// Floral source options (controlled list)
export const floralSourceOptions = [
  'Yellow Box',
  'Ironbark',
  'Manuka',
  'Tea Tree',
  'Blue Gum',
  'Snow Gum',
  'Red Gum',
  'Leatherwood',
  'Clover',
  'Lucerne',
  'Wildflower',
  'Orange Blossom',
  'Macadamia',
  'Banksia',
  'Jarrah',
  'Marri',
  'Native Wildflowers',
];

// Australian states/regions
export const australianRegions = [
  'New South Wales',
  'Victoria',
  'Queensland',
  'South Australia',
  'Western Australia',
  'Tasmania',
  'Northern Territory',
  'Australian Capital Territory',
];

